In [1]:
import numpy as np


In [2]:
a = np.array([1,2,3])
b = np.array([4,6,7.5])
c = a+b
# print(a,b)
c.sort()
print(c)


[ 5.   8.  10.5]


In [3]:
d = np.array([[1,2,3],[4,5,6]])
f = np.array([[8,9,3],[4,5,6]])
e = d*f
e


array([[ 8, 18,  9],
       [16, 25, 36]])

In [6]:
z = np.zeros((3,4))
o = np.ones((2,3))


In [7]:
l = np.linspace(1,2,5)
print(l)

[1.   1.25 1.5  1.75 2.  ]


In [8]:
f = np.full((2,2),7)
print(f)


[[7 7]
 [7 7]]


In [9]:
e = np.eye(5,dtype=int)
print(e)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [10]:
r = np.random.random((3,4))
print(r)


[[0.86085317 0.58673614 0.68108211 0.03950393]
 [0.34309482 0.04707051 0.76499521 0.16071129]
 [0.89900775 0.42726933 0.65152128 0.47563622]]
